### ISSUE TITLE
Send licence type in licence creation 

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-bss#107]
Hi, @srodriguezOPT 
From an analysis made by @felipevicens, it seems that the type of licence is not being sent when the licence is created... can you please check?

**Comment by srodriguezOPT** [comment]
Hi, @jbonnet 

Yes, only the service_uuid is sent because only private services not owned by the user can make the licence request. 

Do we really need to send the licence_type in the request? What value does the GK need?:
- private or to buy (with licenced and owned values the licence request is hidden).

**Comment by jbonnet** [comment]
@srodriguezOPT 
If the GK hardcodes the `PRIVATE` licence type when creating a licence, it can not be used in other cases. I would prefer the BSS, who implements the simple and limited flow we have decided, to pass `PRIVATE` hardcoded as the licence type.

**Comment by jbonnet** [comment]
@srodriguezOPT 
Did you include also the default URL of the Store?

**Comment by srodriguezOPT** [comment]
@jbonnet 
Ok. I can include the service_name

**Comment by srodriguezOPT** [comment]
closed by https://github.com/sonata-nfv/son-bss/pull/108 and https://github.com/sonata-nfv/son-bss/pull/109
